# Generated by Django 5.2.6 on 2025-11-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_usuario_tarefas_concluidas_prazo_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='avatares/default.png', null=True, upload_to='avatares/'),
        ),
    ]
