# Generated by Django 5.2.6 on 2025-11-17 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='foco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.usuariofoco', verbose_name='Área de Foco'),
        ),
    ]
