# Generated by Django 5.2.6 on 2025-11-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_tarefa_foco'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='slots_tarefas_ia_usados',
            field=models.IntegerField(default=0, verbose_name='Slots de tarefas (IA) usados hoje'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo_tarefa',
            field=models.CharField(choices=[('PESSOAL', 'Pessoal'), ('DIARIA', 'Diária (Antigo?)'), ('SEMANAL', 'Semanal (Antigo?)'), ('TEMPLATE_PESSOAL', 'Template Pessoal'), ('IA_DIARIA', 'IA Diária')], default='PESSOAL', max_length=20, verbose_name='Tipo da Tarefa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='slots_tarefas_pessoais_usados',
            field=models.IntegerField(default=0, verbose_name='Slots de tarefas pessoais (Manual) usados hoje'),
        ),
    ]
