# Generated by Django 5.2.6 on 2025-11-18 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemloja',
            options={'verbose_name': 'Item da Loja', 'verbose_name_plural': 'Itens da Loja'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='id_compra',
        ),
        migrations.RemoveField(
            model_name='itemloja',
            name='efeito',
        ),
        migrations.RemoveField(
            model_name='itemloja',
            name='id_item',
        ),
        migrations.RemoveField(
            model_name='itemloja',
            name='preco_moedas',
        ),
        migrations.RemoveField(
            model_name='itemloja',
            name='tipo',
        ),
        migrations.AddField(
            model_name='compra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='compra',
            name='preco_pago',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemloja',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='itemloja',
            name='eh_consumivel',
            field=models.BooleanField(default=True, verbose_name='É Consumível?'),
        ),
        migrations.AddField(
            model_name='itemloja',
            name='icone_bootstrap',
            field=models.CharField(default='bi-box-seam', help_text='Classe do ícone Bootstrap (ex: bi-snow2, bi-lightning-charge)', max_length=50),
        ),
        migrations.AddField(
            model_name='itemloja',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='itemloja',
            name='preco',
            field=models.IntegerField(default=100, verbose_name='Preço (Moedas)'),
        ),
        migrations.AddField(
            model_name='itemloja',
            name='tipo_efeito',
            field=models.CharField(choices=[('CONGELADOR', 'Congelador de Ofensiva'), ('XP_BOOST', 'Dobro de XP (24h)'), ('SLOT_EXTRA', 'Slot de Tarefa Extra'), ('AVATAR', 'Novo Avatar')], default='CONGELADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='itemloja',
            name='valor_efeito',
            field=models.IntegerField(default=1, verbose_name='Valor do Efeito'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.itemloja'),
        ),
        migrations.AlterField(
            model_name='itemloja',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Item'),
        ),
        migrations.CreateModel(
            name='InventarioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade Possuída')),
                ('data_aquisicao', models.DateTimeField(auto_now_add=True)),
                ('esta_ativo', models.BooleanField(default=False, verbose_name='Item em Uso?')),
                ('data_expiracao_efeito', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.itemloja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item no Inventário',
                'verbose_name_plural': 'Inventário dos Usuários',
                'unique_together': {('usuario', 'item')},
            },
        ),
    ]
