# Generated by Django 5.2.6 on 2025-11-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_itemloja_options_remove_compra_id_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='moedas',
            field=models.IntegerField(default=0, verbose_name='Moedas de Ouro'),
        ),
    ]
