# Generated by Django 5.2.6 on 2025-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_usuario_moedas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='congelador_usado_recente',
            field=models.BooleanField(default=False, verbose_name='Notificação Pendente: Congelador'),
        ),
    ]
