# Generated by Django 5.2.6 on 2025-11-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_usuario_congelador_usado_recente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='congelador_usado_recente',
        ),
    ]
