# Generated by Django 5.2.6 on 2025-11-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_usuario_congelador_usado_recente'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemloja',
            name='classe_css',
            field=models.CharField(blank=True, help_text='Ex: moldura-quadrada, moldura-dourada', max_length=50, null=True, verbose_name='Classe CSS (Para Molduras)'),
        ),
        migrations.AlterField(
            model_name='itemloja',
            name='icone_bootstrap',
            field=models.CharField(default='bi-box-seam', help_text='Classe do ícone Bootstrap (ex: bi-snow2)', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemloja',
            name='tipo_efeito',
            field=models.CharField(choices=[('CONGELADOR', 'Congelador de Ofensiva'), ('XP_BOOST', 'Dobro de XP (24h)'), ('SLOT_EXTRA', 'Slot de Tarefa Extra'), ('MOLDURA', 'Moldura de Avatar'), ('AVATAR', 'Novo Avatar')], default='CONGELADOR', max_length=20),
        ),
    ]
