# Generated by Django 5.2.6 on 2025-11-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_itemloja_classe_css_alter_itemloja_icone_bootstrap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloja',
            name='classe_css',
            field=models.CharField(blank=True, help_text='Ex: moldura-quadrada, borda-vermelha, borda-azul', max_length=50, null=True, verbose_name='Classe CSS (Para Molduras/Cores)'),
        ),
        migrations.AlterField(
            model_name='itemloja',
            name='tipo_efeito',
            field=models.CharField(choices=[('CONGELADOR', 'Congelador de Ofensiva'), ('XP_BOOST', 'Dobro de XP (24h)'), ('SLOT_EXTRA', 'Slot de Tarefa Extra'), ('MOLDURA', 'Moldura (Formato)'), ('COR_BORDA', 'Cor da Borda'), ('AVATAR', 'Novo Avatar')], default='CONGELADOR', max_length=20),
        ),
    ]
